#!/bin/bash

#
# Install Eclipse
#

set -e

update-java-alternatives --set java-6-sun 2> /dev/null || true

function install_p2_iu {
  $1 -nosplash -application org.eclipse.equinox.p2.director -metadatarepository $2 -artifactrepository $2 -installIU $3
}

function install_eclipse {
  temp=$(mktemp -d)
  tar -xz -C $temp -f $1
  mv $temp/eclipse /usr/local/$2
  rm -rf $temp

  /usr/local/$2/eclipse -initialize -nosplash

  # Install Subclipse
  for iu in org.tigris.subversion.subclipse.feature.group \
            org.tigris.subversion.subclipse.graph.feature.feature.group \
            org.tigris.subversion.clientadapter.feature.feature.group \
            org.tigris.subversion.clientadapter.javahl.feature.feature.group \
            org.tigris.subversion.clientadapter.svnkit.feature.feature.group \
            org.tmatesoft.svnkit.feature.group \
            net.java.dev.jna.feature.group
  do
    install_p2_iu /usr/local/$2/eclipse http://subclipse.tigris.org/update_1.8.x $iu
  done

  # Install Google App Engine
  for iu in com.google.gdt.eclipse.suite.e37.feature.feature.group \
            com.google.appengine.eclipse.sdkbundle.e37.feature.feature.group
  do
    install_p2_iu /usr/local/$2/eclipse http://dl.google.com/eclipse/plugin/3.7 $iu
  done

  # Include revision in default workspace name
  sed -i "s|user.home/workspace$|user.home/workspace${2#eclipse}|" \
    /usr/local/$2/configuration/config.ini

  # Make Java the default perspective
  sed -i 's|\(.*/defaultPerspectiveId=\).*|\1org.eclipse.jdt.ui.JavaPerspective|' \
    /usr/local/$2/plugins/org.eclipse.*/plugin_customization.ini

  ( cd /usr/local && chown -R root:staff $2 && chmod go-w $2 )

  # Symlinks for easy running
  rm -f /usr/local/eclipse
  ( cd /usr/local && ln -s $2 eclipse)
  if [ ! -h /usr/local/bin/eclipse ]
  then
    ( cd /usr/local/bin && ln -s ../eclipse/eclipse )
  fi
}

for eclipse in /opt/MEET/software/eclipse-*.tar.gz
do
  version=$(basename $eclipse -linux-gtk.tar.gz)
  if [ ! -d /usr/local/$version ]
  then
    install_eclipse $eclipse $version
  fi
done
